ervices:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_prod
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus-data:/prometheus
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_prod
    ports:
      - "3001:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    restart: always

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter_prod
    ports:
      - "9101:9100"
    restart: always
